<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.diwuracreatives</groupId>
    <artifactId>neutrosophic-cache</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>Neutrosophic Cache</name>
    <description>
        A cache replacement policy based on 2-refined neutrosophic integral-based utility functions.
        Eviction decisions are determined by convergence of the improper neutrosophic integral of the first kind.
    </description>
    <url>
        https://github.com/diwuracreatives/neutrosophic-cache-replacement-policy
    </url>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Adediwura Boluwatife</name>
            <email>adediwuraboluwatife1@gmail.com</email>
            <url>https://www.boluwatifeadediwura.xyz</url>
        </developer>
    </developers>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
            <version>3.1.8</version>
        </dependency>
        <dependency>
            <groupId>org.jfree</groupId>
            <artifactId>jfreechart</artifactId>
            <version>1.5.3</version>
        </dependency>
           <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>5.10.2</version>
                <scope>test</scope>
            </dependency>
    </dependencies>
</project>